// <auto-generated />
namespace DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class writer_image_length_250_from_100 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(writer_image_length_250_from_100));
        
        string IMigrationMetadata.Id
        {
            get { return "202201130831046_writer_image_length_250_from_100"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
